// File generated by FlutterFire CLI or manually configured
// https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMASWKtt51Dq-Ixd8WEtC9qbykwitWZrs',
    appId: '1:260454707085:web:20b14fa85372120b7517c4',
    messagingSenderId: '260454707085',
    projectId: 'husltehub-209a8',
    authDomain: 'husltehub-209a8.firebaseapp.com',
    storageBucket: 'husltehub-209a8.firebasestorage.app',
    measurementId: 'G-5J934T985P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5br38S6Y8WQa8dV3V-fYgRa0ocUvXeUw',
    appId: '1:260454707085:android:32b1edef486b08a07517c4',
    messagingSenderId: '260454707085',
    projectId: 'husltehub-209a8',
    storageBucket: 'husltehub-209a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Mlz7jql7_Fp0iAOrKEBPwcwskw_JyoA',
    appId: '1:260454707085:ios:551437d3451098ff7517c4',
    messagingSenderId: '260454707085',
    projectId: 'husltehub-209a8',
    storageBucket: 'husltehub-209a8.firebasestorage.app',
    iosBundleId: 'com.example.hustlehub',
  );

}